run:
  timeout: 10m
  deadline: 5m
linters:
  enable-all: true
  disable:
    - varnamelen
    - exhaustruct
    - depguard
    # deprecated
    - gomnd
    - execinquery
    - exportloopref
    - rowserrcheck
    - wastedassign
linters-settings:
  errcheck:
    check-blank: false
    exclude-functions:
      - fmt:.*
  nolintlint:
    require-specific: true

issues:
  exclude-dirs:
    - demos
  exclude-files:
    - ".*_test.go"
